instrumentation:
    excludes:
        - "cli.js"
        - "index.js"
        - "lib/utils/*.js"
        - "**/*/lib/*Command.js"
        - "out/**"
        - "scripts/**"
        - "systest/**"
check:
    global:
        statements: 50
        branches: 50
        functions: 43
        lines: 50
